function [condrespsignal,constotncu,systemstate] = ...
    getscMRSRCR(formatvars,Dvar,Dc,Qvar,nvar,nc,Lc,M0in,...
    Lengthconstant,Prmc,krogh,multiplier)


[krogh,qO2potentialcons] = findkroghconstants(Dvar,nvar,Lc,M0in,Prmc,krogh);

% Oxygen consumption in each compartment (or attempted oxygen
%  consumption...so long as oxygen is still left)
qO2potentialconsvec = [qO2potentialcons.LA,qO2potentialcons.SA,...
  qO2potentialcons.C];


Lstart = 0;

Qnc = [Qvar.QLA Qvar.QSA Qvar.QC Qvar.QSV Qvar.QLV];
Dnc = [Dvar.DLA Dvar.DSA Dvar.DC Dvar.DSV Dvar.DLV];
Lnc = [Lstart Lc.Leffla Lc.Leffsa Lc.Leffc Lc.Leffsv Lc.Lefflv];

systemstate.endpts.O2Hbsat = zeros(length(Qnc)+1,1);
systemstate.endpts.O2Hbsat(1,:) = Prmc.SA1;
systemstate.endpts.ATPconc = zeros(length(Qnc)+1,1);
systemstate.endpts.ATPconc(1,:) = Prmc.CA1;
systemstate.endpts.PO2 = zeros(length(Qnc)+1,1);
systemstate.endpts.PO2(1,:) = Prmc.PbA1;
systemstate.endpts.CO2 = zeros(length(Qnc)+1,1);
systemstate.endpts.CO2(1,:) = Prmc.CO2init;

Ltotal = cumsum(Lnc);

%  Initializations
systemstate.grid.O2Hbsat(formatvars.nodeslength,length(Qnc)) = 0;
systemstate.grid.ATPconc(formatvars.nodeslength,length(Qnc)) = 0;
systemstate.grid.CO2(formatvars.nodeslength,length(Qnc)) = 0;
systemstate.grid.x(formatvars.nodeslength,length(Qnc)) = 0;
systemstate.grid.qO2cons(formatvars.nodeslength-1,length(Qnc)) = 0;
systemstate.grid.PO2 = zeros(formatvars.nodeslength,length(Qnc));


for j = 1:length(Qnc)-2
    [systemstate.endpts.O2Hbsat(j+1),systemstate.endpts.ATPconc(j+1),...
        systemstate.endpts.CO2(j+1),systemstate.grid.O2Hbsat(:,j),...
        systemstate.grid.ATPconc(:,j),systemstate.grid.CO2(:,j),...
        systemstate.grid.qO2cons(:,j),systemstate.grid.x(:,j)] =...
        uptakecalcanalytic(formatvars,Prmc,qO2potentialconsvec(1,j),Qnc(1,j),...
        Dnc(1,j),Ltotal(1,j),Ltotal(1,j+1),systemstate.endpts.O2Hbsat(j),...
        systemstate.endpts.ATPconc(j),systemstate.endpts.CO2(j));
end

if nargout > 1
    constotncu = sum(sum(diff(systemstate.grid.x(:,1:3)).*...
        bsxfun(@times,[nvar.nLA,nvar.nSA,nvar.nC],...
        systemstate.grid.qO2cons(:,1:3))))/krogh.totalvolume;
end

for j = length(Qnc)-1:length(Qnc)
    systemstate.endpts.O2Hbsat(j+1) = systemstate.endpts.O2Hbsat(j);
    systemstate.grid.O2Hbsat(:,j) = systemstate.endpts.O2Hbsat(j);
    systemstate.endpts.CO2(j+1) = systemstate.endpts.CO2(j);
    systemstate.grid.CO2(:,j) = systemstate.endpts.CO2(j);
    systemstate.endpts.PO2(j+1)= systemstate.endpts.PO2(j);
    
    [systemstate.endpts.ATPconc(j+1),systemstate.grid.ATPconc(:,j),...
        systemstate.grid.x(:,j)] = ...
        upconccalcanalytic(formatvars,Prmc,qO2potentialconsvec(1,end),...
        Qnc(1,j),Dnc(1,j),Ltotal(1,j),Ltotal(1,j+1),...
        systemstate.endpts.O2Hbsat(j),systemstate.endpts.ATPconc(j),...
        systemstate.endpts.CO2(j));
end

saturationtotal = [systemstate.grid.O2Hbsat(:,1);...
    systemstate.grid.O2Hbsat(2:end,2);...
    systemstate.grid.O2Hbsat(2:end,3);...
    systemstate.grid.O2Hbsat(2:end,4);...
    systemstate.grid.O2Hbsat(2:end,5)];
concentrationtotal = [systemstate.grid.ATPconc(:,1);...
    systemstate.grid.ATPconc(2:end,2);...
    systemstate.grid.ATPconc(2:end,3);...
    systemstate.grid.ATPconc(2:end,4);...
    systemstate.grid.ATPconc(2:end,5)];
CO2total = [systemstate.grid.CO2(:,1);...
      systemstate.grid.CO2(2:end,2);...
      systemstate.grid.CO2(2:end,3);...
      systemstate.grid.CO2(2:end,4);...
      systemstate.grid.CO2(2:end,5)];
Pbtotal = [systemstate.grid.PO2(:,1);...
    systemstate.grid.PO2(2:end,2);...
    systemstate.grid.PO2(2:end,3);...
    systemstate.grid.PO2(2:end,4);...
    systemstate.grid.PO2(2:end,5)];


xs = [systemstate.grid.x(:,1);systemstate.grid.x(2:end,2);...
    systemstate.grid.x(2:end,3);systemstate.grid.x(2:end,4);...
    systemstate.grid.x(2:end,5)];


xmid = (Ltotal(2:end)+Ltotal(1:end-1))./2;

%  We only want the signal in the LA (1) and SA (2)
for j = 1:2
    %  Between segment/compartment midpoint and endpoint of lower venule
    inds = (xs > xmid(j)) & (xs < Ltotal(end-1));
    condrespsignal(j) = trapz(xs(inds),concentrationtotal(inds).*...
        exp(-(xs(inds)-xmid(j))/Lengthconstant));
end